# Config file
# Set if the permissions system is enabled
usePermissions: true

# Set if bypass permissions are enabled. usePermissions has to be enabled.
useBypassPermissions: false

# Permissions settings
permissions:
	usePermissions: true
	enableBypassPermissions: true
	permissionsSystems:
		PermissionsEx:
			Enabled: true
		PermissionsBukkit:"
			Enabled: true
		bPermissions:
			Enabled: true
		EssentialsGroupManager:
			Enabled: true
		zPermissions:
			Enabled: true
		Vault:
			Enabled: true
		Permissions:
			Enabled: true

# Tasks settings
tasks:
    updateChecker:
        enabled: true
        interval: 3600
    destructionRepairRepair:
        enabled: true
        interval: 1
    destructionRepairSave:
        enabled: true
        interval: 300

# Update checker
updateChecker:
    enabled: true
    notifyForUpdatesInGame: true
    autoInstallUpdates: true

# Statistics
statistics:
    enabled: true

# Settings for TVNLib
autoDownloadTVNLib: false

# This are the file/folder paths where files are saved
GlobalConfigFilePath: 'plugins/SafeCreeper/global.yml'
WorldConfigsFolderPath: 'plugins/SafeCreeper/worlds'

version: '1.4.2'