# Config file
# Set if the permissions system is enabled
usePermissions: true

# Set if bypass permissions are enabled. usePermissions has to be enabled.
useBypassPermissions: false

# Update checker
updateChecker:
    enabled: true
    notifyForUpdatesInGame: true
    autoInstallUpdates: true

# Statistics
statistics:
    enabled: true

# Set if a message is send to players with permission when they join if there's an update available.
sendMessageWhenUpdateAvailable: true

# Settings for TVNLib
autoDownloadTVNLib: false

# This are the file/folder paths where files are saved
GlobalConfigFilePath: 'plugins/SafeCreeper/global.yml'
WorldConfigsFolderPath: 'plugins/SafeCreeper/worlds'

version: '1.3.7'