name: SafeCreeper
description: 'Get full control of creatures, players and almost everything!'
main: com.timvisee.safecreeper.SafeCreeper
version: ${project.version}
load: startup
author: timvisee
website: http://timvisee.com/
softdepend:
    - PowerNBT
    - Vault
    - TVNLib
    - WorldGuard
    - Corruption
    - MobArena
    - PVPArena
    - Factions
commands:
  safecreeper:
    description: Safe Creeper command
    usage: /safecreeper <arguments>
  sc:
    description: Safe Creeper command
    usage: /sc <arguments>